services:

  # LOGGER SERVICE

  logger-service-1:
    build:
      context: ./logger-service
      dockerfile: Dockerfile
    ports:
      - "28081:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://logger-service-1:8080/logger/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 60s

  logger-service-2:
    build:
      context: ./logger-service
      dockerfile: Dockerfile
    ports:
      - "28082:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://logger-service-2:8080/logger/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 60s

  logger-service-3:
    build:
      context: ./logger-service
      dockerfile: Dockerfile
    ports:
      - "28083:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://logger-service-3:8080/logger/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 60s

  # READER SERVICE

  reader-service-1:
    build:
      context: ./reader-service
      dockerfile: Dockerfile
    ports:
      - "28181:8180"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://reader-service-1:8180/reader/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 60s

  reader-service-2:
    build:
      context: ./reader-service
      dockerfile: Dockerfile
    ports:
      - "28182:8180"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://reader-service-2:8180/reader/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 60s

  reader-service-3:
    build:
      context: ./reader-service
      dockerfile: Dockerfile
    ports:
      - "28183:8180"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://reader-service-3:8180/reader/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 60s

  # WRITER SERVICE

  writer-service-1:
    build:
      context: ./writer-service
      dockerfile: Dockerfile
    ports:
      - "28281:8280"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://writer-service-1:8280/writer/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 60s

  writer-service-2:
    build:
      context: ./writer-service
      dockerfile: Dockerfile
    ports:
      - "28282:8280"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://writer-service-2:8280/writer/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 60s

  writer-service-3:
    build:
      context: ./writer-service
      dockerfile: Dockerfile
    ports:
      - "28283:8280"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://writer-service-3:8280/writer/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 60s

  # BALANCER

  gateway-nginx:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./gateway-nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./gateway-nginx/html/index.html:/usr/share/nginx/html/index.html:ro
    depends_on:

      logger-service-1:
        condition: service_healthy
      logger-service-2:
        condition: service_healthy
      logger-service-3:
        condition: service_healthy

      reader-service-1:
        condition: service_healthy
      reader-service-2:
        condition: service_healthy
      reader-service-3:
        condition: service_healthy

      writer-service-1:
        condition: service_healthy
      writer-service-2:
        condition: service_healthy
      writer-service-3:
        condition: service_healthy
