# extension fields (не сервисы)

x-logger-common: &logger-common
  build:
    context: ./logger-service
    dockerfile: Dockerfile
  networks:
    - default
  healthcheck:
    test: [ "CMD", "curl", "-f", "http://localhost:8080/logger/actuator/health" ]
    interval: 10s
    timeout: 5s
    retries: 6
    start_period: 120s

x-reader-common: &reader-common
  build:
    context: ./reader-service
    dockerfile: Dockerfile
  networks:
    - default
  healthcheck:
    test: [ "CMD", "curl", "-f", "http://localhost:8180/reader/actuator/health" ]
    interval: 10s
    timeout: 5s
    retries: 6
    start_period: 120s
  depends_on:
    logger-service-1:
      condition: service_healthy
    logger-service-2:
      condition: service_healthy
    logger-service-3:
      condition: service_healthy

x-writer-common: &writer-common
  build:
    context: ./writer-service
    dockerfile: Dockerfile
  networks:
    - default
  healthcheck:
    test: [ "CMD", "curl", "-f", "http://localhost:8280/writer/actuator/health" ]
    interval: 10s
    timeout: 5s
    retries: 6
    start_period: 120s
  depends_on:
    logger-service-1:
      condition: service_healthy
    logger-service-2:
      condition: service_healthy
    logger-service-3:
      condition: service_healthy

# Сервисы
services:

  logger-service-1:
    <<: *logger-common
    environment:
      - SERVICE_NUM=1
    ports:
      - "18080:8080"

  logger-service-2:
    <<: *logger-common
    environment:
      - SERVICE_NUM=2
    ports:
      - "28080:8080"

  logger-service-3:
    <<: *logger-common
    environment:
      - SERVICE_NUM=3
    ports:
      - "38080:8080"

  reader-service-1:
    <<: *reader-common
    environment:
      - SERVICE_NUM=1
    ports:
      - "18180:8180"

  reader-service-2:
    <<: *reader-common
    environment:
      - SERVICE_NUM=2
    ports:
      - "28180:8180"

  reader-service-3:
    <<: *reader-common
    environment:
      - SERVICE_NUM=3
    ports:
      - "38180:8180"

  writer-service-1:
    <<: *writer-common
    environment:
      - SERVICE_NUM=1
    ports:
      - "18280:8280"

  writer-service-2:
    <<: *writer-common
    environment:
      - SERVICE_NUM=2
    ports:
      - "28280:8280"

  writer-service-3:
    <<: *writer-common
    environment:
      - SERVICE_NUM=3
    ports:
      - "38280:8280"

  nginx:
    image: nginx:latest
    ports:
      - "3000:80"
    networks:
      - default
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/html/index.html:/usr/share/nginx/html/index.html:ro
    depends_on:
      logger-service-1:
        condition: service_healthy
      logger-service-2:
        condition: service_healthy
      logger-service-3:
        condition: service_healthy
      reader-service-1:
        condition: service_healthy
      reader-service-2:
        condition: service_healthy
      reader-service-3:
        condition: service_healthy
      writer-service-1:
        condition: service_healthy
      writer-service-2:
        condition: service_healthy
      writer-service-3:
        condition: service_healthy

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
