services:

  # LOGGER SERVICE

  logger-service:
    build:
      context: ./logger-service
      dockerfile: Dockerfile
    ports:
      - "28080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/logger/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  # READER SERVICE

  reader-service:
    build:
      context: ./reader-service
      dockerfile: Dockerfile
    ports:
      - "28180:8180"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8180/reader/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  # WRITER SERVICE

  writer-service:
    build:
      context: ./writer-service
      dockerfile: Dockerfile
    ports:
      - "28280:8280"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8280/writer/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  # BALANCER

  nginx:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./gateway-nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./gateway-nginx/html/index.html:/usr/share/nginx/html/index.html:ro
    depends_on:
      logger-service:
        condition: service_healthy
      reader-service:
        condition: service_healthy
      writer-service:
        condition: service_healthy
