# extension fields (не сервисы)

x-eureka-common: &eureka-common
  build:
    context: ./eureka-service
    dockerfile: Dockerfile
  networks:
    - default
  healthcheck:
    test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
    interval: 10s
    timeout: 5s
    retries: 6
    start_period: 120s

x-logger-common: &logger-common
  build:
    context: ./logger-service
    dockerfile: Dockerfile
  networks:
    - default
  healthcheck:
    test: [ "CMD", "curl", "-f", "http://localhost:8080/logger/actuator/health" ]
    interval: 10s
    timeout: 5s
    retries: 6
    start_period: 120s
  depends_on:
    eureka-service-1:
      condition: service_healthy
    eureka-service-2:
      condition: service_healthy
    eureka-service-3:
      condition: service_healthy

x-reader-common: &reader-common
  build:
    context: ./reader-service
    dockerfile: Dockerfile
  networks:
    - default
  healthcheck:
    test: [ "CMD", "curl", "-f", "http://localhost:8180/reader/actuator/health" ]
    interval: 10s
    timeout: 5s
    retries: 6
    start_period: 120s
  depends_on:
    eureka-service-1:
      condition: service_healthy
    eureka-service-2:
      condition: service_healthy
    eureka-service-3:
      condition: service_healthy
    logger-service-1:
      condition: service_healthy
    logger-service-2:
      condition: service_healthy
    logger-service-3:
      condition: service_healthy

x-writer-common: &writer-common
  build:
    context: ./writer-service
    dockerfile: Dockerfile
  networks:
    - default
  healthcheck:
    test: [ "CMD", "curl", "-f", "http://localhost:8280/writer/actuator/health" ]
    interval: 10s
    timeout: 5s
    retries: 6
    start_period: 120s
  depends_on:
    eureka-service-1:
      condition: service_healthy
    eureka-service-2:
      condition: service_healthy
    eureka-service-3:
      condition: service_healthy
    logger-service-1:
      condition: service_healthy
    logger-service-2:
      condition: service_healthy
    logger-service-3:
      condition: service_healthy

x-gateway-common: &gateway-common
  build:
    context: ./gateway-service
    dockerfile: Dockerfile
  networks:
    - default
  healthcheck:
    test: [ "CMD", "curl", "-f", "http://localhost:8090/actuator/health" ]
    interval: 10s
    timeout: 5s
    retries: 6
    start_period: 120s
  depends_on:
    eureka-service-1:
      condition: service_healthy
    eureka-service-2:
      condition: service_healthy
    eureka-service-3:
      condition: service_healthy
    logger-service-1:
      condition: service_healthy
    logger-service-2:
      condition: service_healthy
    logger-service-3:
      condition: service_healthy
    reader-service-1:
      condition: service_healthy
    reader-service-2:
      condition: service_healthy
    reader-service-3:
      condition: service_healthy
    writer-service-1:
      condition: service_healthy
    writer-service-2:
      condition: service_healthy
    writer-service-3:
      condition: service_healthy

# Сервисы
services:

  eureka-service-1:
    <<: *eureka-common
    environment:
      - SERVICE_NUM=1
    ports:
      - "18761:8761"

  eureka-service-2:
    <<: *eureka-common
    environment:
      - SERVICE_NUM=2
    ports:
      - "28761:8761"

  eureka-service-3:
    <<: *eureka-common
    environment:
      - SERVICE_NUM=3
    ports:
      - "38761:8761"

  logger-service-1:
    <<: *logger-common
    environment:
      - SERVICE_NUM=1

  logger-service-2:
    <<: *logger-common
    environment:
      - SERVICE_NUM=2

  logger-service-3:
    <<: *logger-common
    environment:
      - SERVICE_NUM=3

  reader-service-1:
    <<: *reader-common
    environment:
      - SERVICE_NUM=1

  reader-service-2:
    <<: *reader-common
    environment:
      - SERVICE_NUM=2

  reader-service-3:
    <<: *reader-common
    environment:
      - SERVICE_NUM=3

  writer-service-1:
    <<: *writer-common
    environment:
      - SERVICE_NUM=1

  writer-service-2:
    <<: *writer-common
    environment:
      - SERVICE_NUM=2

  writer-service-3:
    <<: *writer-common
    environment:
      - SERVICE_NUM=3

  gateway-service-1:
    <<: *gateway-common
    environment:
      - SERVICE_NUM=1
    ports:
      - "18090:8090"

  gateway-service-2:
    <<: *gateway-common
    environment:
      - SERVICE_NUM=2
    ports:
      - "28090:8090"

  gateway-service-3:
    <<: *gateway-common
    environment:
      - SERVICE_NUM=3
    ports:
      - "38090:8090"

  nginx:
    image: nginx:latest
    ports:
      - "3000:80"
    networks:
      - default
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/html/index.html:/usr/share/nginx/html/index.html:ro
    depends_on:
      gateway-service-1:
        condition: service_healthy
      gateway-service-2:
        condition: service_healthy
      gateway-service-3:
        condition: service_healthy

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
