server:
  port: 8080
  servlet:
    context-path: /logger

spring:
  application:
    name: logger-service

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health

logging:
  level:
    root: INFO
    ru.digitalleague.gatewaydemo: DEBUG
    org.apache.catalina.core: WARN
    org.springframework.web.servlet: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level --- [%15.15thread] %40.40logger : %msg%n"
